#!/bin/bash

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                  📤 GUÍA: PUBLICAR EN GITHUB                              ║
# ║              Hola Suite Dashboard - v2.1                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║         📤 GUÍA PASO A PASO: SUBIR A GITHUB                               ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"

echo ""
echo "✅ El repositorio git YA ESTÁ INICIADO con el primer commit"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "PASO 1: Crear repositorio en GitHub"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Ir a: https://github.com/new"
echo "2. Nombre del repositorio: hola-suite"
echo "3. Descripción: Sistema de gestión de clientes y vendedores con ClickUp"
echo "4. Seleccionar: Public (para que sea público)"
echo "5. NO marcar: 'Initialize with README' (ya tenemos uno)"
echo "6. Crear repositorio"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "PASO 2: Agregar el remote de GitHub"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Después de crear el repo, GitHub te mostrará estos comandos."
echo "Ejecutar en terminal (reemplaza TU_USUARIO):"
echo ""
echo "  git remote add origin https://github.com/TU_USUARIO/hola-suite.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "PASO 3: Ejemplo completo de comandos"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "# Ver el estado actual"
echo "git status"
echo ""
echo "# Ver el log de commits"
echo "git log"
echo ""
echo "# Agregar remoto (reemplaza con tu usuario y email)"
echo "git remote add origin https://github.com/tu-usuario/hola-suite.git"
echo ""
echo "# Cambiar rama master a main"
echo "git branch -M main"
echo ""
echo "# Subir los cambios a GitHub"
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "PASO 4: Futuras actualizaciones"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Cuando hagas cambios y quieras subirlos:"
echo ""
echo "  # Ver qué cambió"
echo "  git status"
echo ""
echo "  # Agregar todos los cambios"
echo "  git add -A"
echo ""
echo "  # Commit con descripción"
echo "  git commit -m 'Descripción de los cambios'"
echo ""
echo "  # Subir a GitHub"
echo "  git push origin main"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "INFORMACIÓN DEL REPOSITORIO LOCAL"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

cd "/home/ixcsoft/Dashboard- Hola suite"

echo "📁 Ubicación:"
pwd

echo ""
echo "🔍 Estado git:"
git status

echo ""
echo "📋 Últimos commits:"
git log --oneline | head -5

echo ""
echo "🔗 Remoto actual:"
git remote -v 2>/dev/null || echo "⚠️ Sin remoto configurado aún"

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "✨ ¡LISTO!"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Una vez crees el repositorio en GitHub, ejecuta:"
echo ""
echo "  git remote add origin https://github.com/TU_USUARIO/hola-suite.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "✅ Luego tu código estará en GitHub!"
echo ""
